//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ARMLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenant
    {
        public int IdTenant { get; set; }
        public string loginTenant { get; set; }
        public string paswordTenant { get; set; }
        public Nullable<int> idViewUser { get; set; }
    }
}
